const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/item-1.jpeg',
      desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, porro! Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, porro!`,
    },
    {
      id: 2,
      title: 'lunch double',
      category: 'lunch',
      price: 13.99,
      img: './images/item-2.jpeg',
      desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, porro!`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et facilis rem sit. Optio, ipsam modi?`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et facilis rem sit. Optio, ipsam modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, porro!`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Est officiis perferendis numquam aut?`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et facilis rem sit. Optio, ipsam modi?`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Est officiis perferendis numquam aut?`,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Est officiis perferendis numquam aut?`,
    },
    {
      id: 9,
      title: 'dinner delight',
      category: 'dinner',
      price: 30.99,
      img: './images/item-10.jpeg',
      desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, porro!`,
    },
  ];
  export default menu;